CREATE DATABASE SpMedicalGroup;
GO

USE SpMedicalGroup;
GO

CREATE TABLE TIPOS_USUARIOS (
	ID INT PRIMARY KEY IDENTITY NOT NULL  
	, NOME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE USUARIOS (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, EMAIL VARCHAR(255) UNIQUE NOT NULL
	, SENHA VARCHAR(255) NOT NULL
	, ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS(ID) NOT NULL
);

CREATE TABLE PRONTUARIOS (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, NOME VARCHAR(255) NOT NULL
	, RG CHAR(14) UNIQUE NOT NULL
	, CPF CHAR(11) UNIQUE NOT NULL
	, DATA_NASCIMENTO DATE NOT NULL
	, TELEFONE VARCHAR(20)
	, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
	, RUA VARCHAR(255) NOT NULL
	, BAIRRO VARCHAR(255)
	, CIDADE VARCHAR(255) NOT NULL
	, ESTADO CHAR(2) NOT NULL
	, CEP CHAR(9) UNIQUE NOT NULL
);

CREATE TABLE CLINICAS (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, NOME_FANTASIA VARCHAR(255) UNIQUE NOT NULL
	, RAZAO_SOCIAL VARCHAR(255)
	, HORARIO_FUNCIONAMENTO VARCHAR(255) NOT NULL
	, CNPJ CHAR(18) NOT NULL
	, RUA VARCHAR(255) NOT NULL
	, BAIRRO VARCHAR(255)
	, CIDADE VARCHAR(250) NOT NULL
	, ESTADO CHAR(2) NOT NULL
	, CEP CHAR(9) UNIQUE NOT NULL
);

CREATE TABLE ESPECIALIDADES (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, NOME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE MEDICOS (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, NOME VARCHAR(255) NOT NULL
	, CRM VARCHAR(255) UNIQUE NOT NULL
	, ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL
	, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
	, ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID) NOT NULL
);

CREATE TABLE SITUACAO (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, NOME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE CONSULTAS (
	ID INT PRIMARY KEY IDENTITY NOT NULL
	, ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIOS(ID) NOT NULL
	, ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL
	, DATA_AGENDADA DATE NOT NULL
	, HORA_AGENDADA TIME NOT NULL
	, ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO(ID) DEFAULT 1
	, DESCRICAO TEXT
);

--- INDICES

CREATE NONCLUSTERED INDEX IDX_PRONTUARIOS_CPF
	ON PRONTUARIOS (CPF);
GO

CREATE NONCLUSTERED INDEX IDX_USUARIOS_EMAIL
	ON USUARIOS (EMAIL);
GO

CREATE NONCLUSTERED INDEX IDX_MEDICOS_CRM
	ON MEDICOS (CRM);
GO

CREATE NONCLUSTERED INDEX IDX_CONS_ID_PRONT
	ON CONSULTAS (ID_PRONTUARIO);
GO

CREATE NONCLUSTERED INDEX IDX_CONS_ID_MEDICO
	ON CONSULTAS (ID_MEDICO);
GO

CREATE NONCLUSTERED INDEX IDX_CONS_DATA
	ON CONSULTAS (DATA_AGENDADA);
GO 

--- FUNCTIONS

--- RETORNA A QUANTIDADE DE MEDICOS QUE TEM AQUELA ESPECIALIDADE
CREATE FUNCTION dbo.QUANT_MED_ESP(@ESPECI int)
RETURNS TABLE
AS
RETURN
	SELECT COUNT(ID) AS QUANT_MEDI_ESPECI FROM MEDICOS AS MEDI WHERE MEDI.ID_ESPECIALIDADE = @ESPECI;
GO

--- RETORNA OS MEDICOS COM TEM AQUELA ESPECIALIDADE
CREATE FUNCTION MED_ESP(@ESPECI INT)
RETURNS TABLE
AS
RETURN
	SELECT * FROM MEDICOS WHERE ID_ESPECIALIDADE = @ESPECI;
GO

--- PROCEDURE

--- CALCULA A IDADE DE UM PACIENTE USANDO PROCEDURE
CREATE PROCEDURE IDADE_DATA_NASC
@DATA_NASC DATE
AS 
SELECT DATEDIFF(MONTH, @DATA_NASC, GETDATE())/12 AS IDADE;
GO